import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const core=await readFile(new URL('../components/intake-core.jsx',import.meta.url),'utf8');
const store=(await readFile(new URL('../components/store.jsx',import.meta.url),'utf8')).split('function StoreProvider')[0];
const seedSource=await readFile(new URL('../components/model-data.jsx',import.meta.url),'utf8');
function context(){const c=vm.createContext({window:{},URL,React:{createContext:()=>({})}});vm.runInContext(seedSource,c);vm.runInContext(core,c);vm.runInContext(store,c);return c;}
function complete(c,id='ri-test'){
 const p=c.newIntakeProject(id,'pre_funding','2026-10-01');Object.assign(p,{name:'Test property',sponsor:'Test sponsor',address:'25 Dorrance St',municipality:'Providence',developmentType:'Conversion / adaptive reuse',objective:'Plan lease-up'});
 Object.assign(p.draft,{totalUnits:'10',deliveryDate:'2027-01-01',targetDate:'2027-04-01',targetOccupancy:'100',leasesPerWeek:'7',freeMonths:'1',leaseTerm:'12',marketing:'1000',staffing:'2000',monthlyCarry:'3043.75',strategy:'In-house',researchReviewed:true,unitMix:[{label:'1BR',count:'10',sqft:'700',rent:'2400',leased:'0',availableDate:''}]});return p;
}
test('all 39 RI municipalities are supported as intake choices; new projects have no inherited model',()=>{const c=context(),p=c.newIntakeProject('ri-a','pre_funding','now');assert.equal(c.window.RI_TOWNS.length,39);assert.equal(new Set(c.window.RI_TOWNS).size,39);assert.equal(p.draft.unitMix.length,0);assert.equal(p.baselines.length,0);assert.ok(c.intakeIssues(p).length>10);assert.equal(c.calculateIntake(p).scenarios.length,0);});
test('creating and editing two projects never mutates the demo or another project',()=>{const c=context();let s=c.restoreIntakeState(c.window.SEED,{getItem:()=>null});const seed=JSON.stringify(s.projects[0]);s=c.reducer(s,{type:'createIntakeProject',id:'ri-a'});s=c.reducer(s,{type:'createIntakeProject',id:'ri-b'});s=c.reducer(s,{type:'editIntakeProject',projectId:'ri-a',patch:{name:'A'},draft:{totalUnits:'10'}});assert.equal(s.projects.find(p=>p.id==='ri-b').draft.totalUnits,'');assert.equal(JSON.stringify(s.projects[0]),seed);});
test('model calculates rent, concessions, carry and sensitivities from project values',()=>{const c=context(),p=complete(c),r=c.calculateIntake(p);assert.equal(r.issues.length,0);assert.equal(r.averageRent,2400);assert.equal(r.effectiveRent,2200);assert.equal(r.grossMonthlyRent,24000);const b=r.scenarios[1];assert.equal(b.elapsedDays,10);assert.equal(b.stabilizeDate,'2027-01-11');assert.equal(b.concessionCost,24000);assert.equal(b.carryCost,1000);assert.equal(b.totalCost,28000);p.draft.unitMix[0].rent='3000';assert.equal(c.calculateIntake(p).scenarios[1].totalCost,34000);assert.ok(r.scenarios[0].elapsedDays>b.elapsedDays);});
test('later delivery phases cannot lease early, and existing leased units are not leased again',()=>{const c=context(),p=complete(c);p.draft.unitMix[0].availableDate='2027-02-01';p.draft.unitMix[0].leased='5';const r=c.calculateIntake(p);assert.equal(r.scenarios[1].stabilizeDate,'2027-02-06');assert.equal(r.scenarios[1].concessionCost,12000);assert.equal(r.existingLeased,5);});
test('validation rejects mismatched totals, invalid dates, zero rents, missing explicit budgets and bad occupancy',()=>{const c=context();for(const mutate of [p=>p.draft.totalUnits='11',p=>p.draft.deliveryDate='2027-02-30',p=>p.draft.targetDate='2026-01-01',p=>p.draft.marketing='',p=>p.draft.targetOccupancy='101',p=>p.draft.freeMonths='13',p=>p.draft.unitMix[0].rent='0',p=>p.draft.unitMix[0].leased='11',p=>p.draft.unitMix[0].count='1.5']){const p=complete(c);mutate(p);assert.ok(c.intakeIssues(p).length);assert.equal(c.calculateIntake(p).scenarios.length,0);}});
test('baseline is a snapshot, repeated approval is idempotent, edits invalidate approval and history survives',()=>{const c=context(),p=complete(c);let s={...c.restoreIntakeState(c.window.SEED,{getItem:()=>null}),projects:[p]};s=c.reducer(s,{type:'approveIntakeBaseline',projectId:p.id,id:'b1',at:'now'});assert.equal(s.projects[0].baselines.length,1);assert.equal(s.unitTypes.filter(u=>u.projectId===p.id).length,1);s=c.reducer(s,{type:'approveIntakeBaseline',projectId:p.id,id:'b2'});assert.equal(s.projects[0].baselines.length,1);s=c.reducer(s,{type:'editIntakeProject',projectId:p.id,draft:{step:2},navigationOnly:true});assert.equal(s.projects[0].approvedBaselineId,'b1');s=c.reducer(s,{type:'editIntakeProject',projectId:p.id,draft:{marketing:'9000'}});assert.equal(s.projects[0].approvedBaselineId,null);assert.equal(s.projects[0].baselines[0].project.draft.marketing,'1000');});
test('save/reload preserves draft, approval and approved unit types without persisting seed operational data',()=>{const c=context(),p=complete(c);let s={...c.restoreIntakeState(c.window.SEED,{getItem:()=>null}),projects:[p],activeProjectId:p.id};s=c.reducer(s,{type:'approveIntakeBaseline',projectId:p.id,id:'b1',at:'now'});let raw;const storage={setItem:(key,value)=>raw=value,getItem:()=>raw};c.persistIntakeState(s,storage);assert.equal(JSON.parse(raw).leads,undefined);const r=c.restoreIntakeState(c.window.SEED,storage);assert.equal(r.activeProjectId,p.id);assert.equal(r.projects.find(x=>x.id===p.id).approvedBaselineId,'b1');assert.equal(r.unitTypes.find(x=>x.projectId===p.id).askingRent,2400);});
test('corrupt or inaccessible storage is surfaced and not overwritten',()=>{const c=context();for(const getItem of [()=>'{',()=>{throw new Error('denied');}]){const s=c.restoreIntakeState(c.window.SEED,{getItem});assert.ok(s.storageError);assert.throws(()=>c.persistIntakeState(s,{setItem:()=>assert.fail('must preserve old data')}));}});
test('CSV handles quoted commas and rejects malformed or missing columns; evidence URLs reject javascript',()=>{const c=context(),rows=c.parseIntakeCSV('label,count,sqft,rent,leased,availableDate\n"1BR, phase A",10,700,2400,0,2027-01-01\n');assert.equal(rows[0].label,'1BR, phase A');assert.equal(rows[0].availableDate,'2027-01-01');assert.throws(()=>c.parseIntakeCSV('name,count\nA,1'));assert.throws(()=>c.parseIntakeCSV('"unclosed'));assert.equal(c.intakeSafeURL('javascript:alert(1)'),null);});

test('setup needs only a named property and municipality, not underwriting or research',()=>{const c=context(),p=c.newIntakeProject('ri-short','pre_funding','now');assert.equal(c.projectSetupIssues(p).length,3);Object.assign(p,{name:'New property',address:'10 Main Street',municipality:'Providence'});assert.equal(c.projectSetupIssues(p).length,0);assert.ok(c.intakeIssues(p).length>0);let s={...c.restoreIntakeState(c.window.SEED,{getItem:()=>null}),projects:[p]};s=c.reducer(s,{type:'finishProjectSetup',projectId:p.id,at:'2026-10-01'});assert.equal(c.intakeLanding(s.projects[0]),'home');assert.equal(s.projects[0].baselines.length,0);let raw;c.persistIntakeState(s,{setItem:(_,v)=>raw=v});const restored=c.restoreIntakeState(c.window.SEED,{getItem:()=>raw});assert.equal(c.intakeLanding(restored.projects.find(x=>x.id===p.id)),'home');});
test('invalid setup cannot finish; existing completed intake opens the project without losing data',()=>{const c=context(),p=complete(c);let s={...c.restoreIntakeState(c.window.SEED,{getItem:()=>null}),projects:[p]};p.address='';assert.equal(c.reducer(s,{type:'finishProjectSetup',projectId:p.id,at:'now'}),s);p.draft.step=5;assert.equal(c.intakeLanding(p),'home');assert.equal(p.draft.unitMix[0].rent,'2400');});
test('optional research and sponsor fields do not block an otherwise complete model',()=>{const c=context(),p=complete(c);p.sponsor='';p.objective='';p.developmentType='';p.draft.researchReviewed=false;p.draft.unitMix[0].sqft='';assert.equal(c.calculateIntake(p).issues.length,0);});

test('town comes from an address city segment, never a street substring or an out-of-state place',()=>{const c=context();assert.equal(c.intakeMunicipality('25 Dorrance St, Providence, RI 02903'),'Providence');assert.equal(c.intakeMunicipality('12 Providence Street, Cranston, RI'),'Cranston');assert.equal(c.intakeMunicipality('12 Providence Street'),'');assert.equal(c.intakeMunicipality('10 Main St, Warwick, MA',{state:'MA',municipality:'Warwick'}),'');assert.equal(c.intakeMunicipality('address',{state:'RI',municipality:'North Providence'}),'North Providence');});
test('25-unit buildings open in all three stages without rent, budget or unit-mix homework',()=>{const c=context();for(const stage of ['pre_funding','funded_prelaunch','active_leaseup']){const p=c.newIntakeProject('25-'+stage,stage,'now');Object.assign(p,{name:'25 Dorrance St',address:'25 Dorrance St, Providence, RI',municipality:'Providence'});p.draft.totalUnits='25';assert.equal(c.projectSetupIssues(p).length,0);const s=c.reducer({projects:[p]},{type:'finishProjectSetup',projectId:p.id,at:'now'});assert.equal(c.intakeLanding(s.projects[0]),'home');assert.equal(c.intakeProjectFocus(p).count,25);assert.equal(c.intakeProjectFocus(p).section,stage==='pre_funding'?2:1);assert.equal(p.draft.unitMix.length,0);assert.equal(p.draft.marketing,'');}});

test('dashboard shows saved building figures and preserves unknown leasing positions',()=>{const c=context(),p=c.newIntakeProject('dash','active_leaseup','now');p.draft.totalUnits='25';assert.equal(c.projectDashboardFacts(p).total,25);assert.equal(c.projectDashboardFacts(p).leased,null);p.draft.unitMix=[{count:'25',leased:'20'}];assert.equal(c.projectDashboardFacts(p).remaining,5);assert.equal(c.projectDashboardFacts(p).occupancy,80);for(const leased of ['', '26','-1']){p.draft.unitMix[0].leased=leased;assert.equal(c.projectDashboardFacts(p).leased,null);}p.draft.unitMix=[{count:'20',leased:'10'}];assert.equal(c.projectDashboardFacts(p).remaining,null);});
test('switching to an example dashboard survives reload without losing real drafts',()=>{const c=context(),p=complete(c);let s={...c.restoreIntakeState(c.window.SEED,{getItem:()=>null})};s.projects.push(p);s.activeProjectId=s.projects[0].id;let raw;c.persistIntakeState(s,{setItem:(_,v)=>raw=v});const r=c.restoreIntakeState(c.window.SEED,{getItem:()=>raw});assert.equal(r.activeProjectId,s.activeProjectId);assert.ok(r.projects.some(x=>x.id===p.id));});
