import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const c=vm.createContext({window:{},URLSearchParams,Date,React:{createContext:()=>({})}});
for(const f of ['model-data','intake-core','providence-gis','market-data','market-core','store']){let s=await readFile(new URL(`../components/${f}.jsx`,import.meta.url),'utf8');if(f==='store')s=s.split('function StoreProvider')[0];vm.runInContext(s,c);}
const project=()=>({...c.newIntakeProject('test','pre_funding','now'),name:'Test',municipality:'Providence',address:'25 Dorrance Street, Providence, RI'});
const feature=(id,address,lat=41.824)=>({attributes:{OBJECTID:id,ParcAddress:address,MuniUseCodeDesc:'Apartments',NumUnits:'20'},geometry:{rings:[[[-71.413,lat],[-71.412,lat],[-71.412,lat+.001],[-71.413,lat]]]}});
const response=features=>({ok:true,json:async()=>({features})});
test('address normalization excludes the subject despite unit and suffix spelling',()=>{assert.equal(c.marketAddress('25 Dorrance Street Apt 2, Providence'),'25 DORRANCE ST');const p=project();p.address='12 Eagle St';assert.ok(!c.rankMarketEvidence(p,null).some(x=>x.name==='US Rubber Lofts'));});
test('live discovery requires a unique exact address, excludes subject, drops geometry, and forwards cancellation',async()=>{const p=project(),calls=[],signal={};const r=await c.discoverMarket(p,{signal,fetcher:async(url,options)=>{calls.push(url);assert.equal(options.signal,signal);return response(calls.length===1?[feature(1,'25 Dorrance St')]:[feature(1,'25 Dorrance St'),feature(2,'12 Eagle St')]);}});assert.equal(r.subject.id,'1');assert.equal(r.candidates.length,1);assert.equal(r.candidates[0].rings,undefined);assert.match(decodeURIComponent(calls[1].replaceAll('+',' ')),/MuniUseCodeDesc = 'Apartments'/);});
test('ambiguous addresses and unsupported municipalities do not fabricate discovery',async()=>{let calls=0;const r=await c.discoverMarket(project(),{fetcher:async()=>{calls++;return response([feature(1,'25 Dorrance St'),feature(2,'25 Dorrance St')]);}});assert.equal(r.status,'ambiguous');assert.equal(r.subject,null);assert.equal(calls,1);const p=project();p.municipality='Warwick';const outside=await c.discoverMarket(p,{fetcher:()=>assert.fail('outside coverage')});assert.equal(outside.status,'outside');assert.equal(c.rankMarketEvidence(p,null).length,0);});
test('lookup errors are visible and truncated address matches are never selected',async()=>{await assert.rejects(c.discoverMarket(project(),{fetcher:async()=>({ok:false})}),/unavailable/);await assert.rejects(c.discoverMarket(project(),{fetcher:async()=>({ok:true,json:async()=>({features:[],exceededTransferLimit:true})})}),/several address matches/);});
const quote=(id,price,basis='advertised-rent',extra={})=>({id,name:id,basis,reviewedAt:'2026-10-01',plans:[{beds:1,price,status:'advertised'}],...extra});
const now=new Date('2026-10-01T12:00:00Z');
test('market ranges count each property once and keep fee bases separate',()=>{const a=quote('a',2000);a.plans.push({beds:1,price:2500,status:'advertised'});const g=c.marketSignals([a,quote('b',2200),quote('c',2300,'monthly-total')],{now});assert.equal(g.length,2);const rent=g.find(x=>x.basis==='advertised-rent');assert.equal(rent.count,2);assert.equal(rent.min,2000);assert.equal(rent.max,2200);});
test('excluded, stale, future, invalid date, waitlist, restricted and unknown quotes never enter signals',()=>{const data=[quote('excluded',2000,'advertised-rent',{excluded:true}),quote('old',2000,'advertised-rent',{reviewedAt:'2026-08-01'}),quote('future',2000,'advertised-rent',{reviewedAt:'2026-11-01'}),quote('invalid',2000,'advertised-rent',{reviewedAt:'bad'}),quote('range',2000,'unallocated-range'),...['waitlist','contact'].map(status=>quote(status,0,'advertised-rent',{plans:[{beds:1,price:2000,status}]})),quote('restricted',0,'advertised-rent',{plans:[{beds:1,price:2000,status:'advertised',restricted:true}]}),quote('missing',null)];assert.equal(c.marketSignals(data,{now}).length,0);});
test('matching explains uncertainty and responds to owner profile without inventing distance',()=>{const p=project();p.developmentType='Conversion / adaptive reuse';p.draft.unitMix=[{label:'1BR',sqft:'705'}];const e=c.rankMarketEvidence(p,null);assert.ok(e[0].reasons.includes('Matches historic conversion profile'));assert.ok(e.every(x=>x.reasons.includes('Exact site distance not established')));p.marketExcluded=[e[0].id];assert.equal(c.rankMarketEvidence(p,null)[0].excluded,true);});
test('late GIS results cannot overwrite a moved property; comparison selections preserve approval and persist',()=>{const p=project();p.approvedBaselineId='baseline';const old=c.marketFingerprint(p);p.address='12 Eagle St';let s={projects:[p],activeProjectId:p.id};s=c.reducer(s,{type:'saveMarketDiscovery',projectId:p.id,fingerprint:old,data:{status:'ready'}});assert.equal(s.projects[0].marketData,undefined);s=c.reducer(s,{type:'setMarketExcluded',projectId:p.id,compId:'station-row',excluded:true});assert.equal(s.projects[0].approvedBaselineId,'baseline');let raw;c.persistIntakeState(s,{setItem:(_,v)=>raw=v});assert.equal(JSON.parse(raw).projects[0].marketExcluded[0],'station-row');});
