/* global React, PropertyLocation, RI_TOWNS, intakeIssues, calculateIntake, parseIntakeCSV, intakeSafeURL */
const INTAKE_STEPS = [
  ["The project","Place, purpose & ownership"], ["The building","Unit schedule & delivery"],
  ["The evidence","Public records & market research"], ["The rents","Pricing & concessions"],
  ["The plan","Timing, budget & execution"], ["Review","Scenarios & approved baseline"]
];
const intakeMoney = value => value == null ? "—" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
function IntakeField({label,value,onChange,type="text",children,hint,...rest}) {
  return <label className="ri-field"><span>{label}</span>{children || <input type={type} value={value ?? ""} onChange={e=>onChange(e.target.value)} onInput={type==="date" ? e=>onChange(e.currentTarget.value) : undefined} {...rest} />}{hint && <small>{hint}</small>}</label>;
}
function IntakeWorkspace({t,project,initialView,entryStep=0,embedded=false,onDashboard,onNewProject}) {
  const {state,dispatch,saveStatus} = useStore();
  const [view,setView]=React.useState(()=>initialView||intakeLanding(project));
  const market=useProjectMarket(project,dispatch,view!=="setup");
  const [localStep,setLocalStep]=React.useState(entryStep);
  const goHome=()=>onDashboard?onDashboard():setView("home");
  const d=project.draft, step=embedded?localStep:d.step, issues=intakeIssues(project), output=calculateIntake(project);
  const [unitDetails,setUnitDetails]=React.useState(false);
  const unitColumns=unitDetails?["label","count","sqft","rent","leased","availableDate"]:project.stage==="active_leaseup"?["label","count","rent","leased"]:["label","count","rent"];
  const [csv,setCSV]=React.useState(""), [importRows,setImportRows]=React.useState(null), [message,setMessage]=React.useState("");
  React.useEffect(()=>{window.scrollTo({top:0,behavior:"instant"});},[step,project.id,view]);
  const edit=(patch={},draft={},navigationOnly=false)=>dispatch({type:"editIntakeProject",projectId:project.id,patch,draft,navigationOnly,at:new Date().toISOString()});
  React.useEffect(()=>{if(view==="home" && !project.workspaceOpenedAt) edit({workspaceOpenedAt:new Date().toISOString()}, {},true);},[view,project.workspaceOpenedAt,project.id]);
  const openSection=index=>{setLocalStep(index);edit({}, {step:index},true);setView("edit");setMessage("");};

  const field=(key,label,type="text",hint)=> <IntakeField label={label} type={type} value={d[key]} onChange={value=>edit({}, {[key]:value})} hint={hint} />;
  const projectField=(key,label,hint)=> <IntakeField label={label} value={project[key]} onChange={value=>edit(key==="address"?{address:value,location:null}:{[key]:value})} hint={hint} />;
  const changeRow=(index,key,value)=>edit({}, {unitMix:d.unitMix.map((r,i)=>i===index?{...r,[key]:value}:r)});
  const newProject=()=>onNewProject?onNewProject():setView("welcome");
  const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const exportProject=()=>download((project.name || "LeaseRight")+".json",JSON.stringify({format:"leaseright-project",version:1,project},null,2),"application/json");
  const restoreProject=async event=>{
    const file=event.target.files?.[0];event.target.value="";if(!file)return;
    try {
      if(file.size>5000000)throw new Error("Choose a project backup smaller than 5 MB.");
      const saved=JSON.parse(await file.text());
      if(saved.format!=="leaseright-project" || saved.version!==1 || !validIntakeDraft(saved.project))throw new Error("Choose a LeaseRight project backup exported from this intake.");
      const id="ri-"+crypto.randomUUID();
      dispatch({type:"createIntakeProject",id,stage:saved.project.stage,at:new Date().toISOString()});
      const p=saved.project;
      // Import only project-owned fields; approval must be reviewed again in the new project.
      dispatch({type:"editIntakeProject",projectId:id,patch:{name:p.name,address:p.address,sponsor:p.sponsor,municipality:p.municipality,objective:p.objective,developmentType:p.developmentType,location:null,baselines:p.baselines,workspaceOpenedAt:new Date().toISOString()},draft:p.draft,at:new Date().toISOString()});
    }catch(error){setMessage(error.message);}
  };
  const rowCount=d.unitMix.reduce((sum,r)=>sum+(Number(r.count)||0),0);
  const approved=project.baselines.find(b=>b.id===project.approvedBaselineId);
  const focus=intakeProjectFocus(project);
  const knownPosition=d.unitMix.length>0 && rowCount===focus.count && d.unitMix.every(r=>intakeNumber(r.leased)!==null && Number.isInteger(+r.leased) && +r.leased>=0 && +r.leased<=+r.count);
  const leasedCount=knownPosition?d.unitMix.reduce((n,r)=>n+(+r.leased),0):null;
  if(view==="welcome" || view==="stage" || view==="intro")return <LeaseRightWelcome t={t} initialStep={view==="stage"?"stage":"welcome"} initialStage={project.stage} contextLabel={view==="stage"?project.name:"New project"} continueLabel={view==="stage"&&project.workspaceOpenedAt?"Return to project →":"Find the property →"} onCancel={()=>setView(initialView==="setup"?"setup":embedded?"edit":intakeLanding(project))} onComplete={stage=>{if(view!=="welcome"){edit({stage},{},stage===project.stage);setView(initialView==="setup"?"setup":embedded?"edit":intakeLanding(project));}else dispatch({type:"createIntakeProject",id:"ri-"+crypto.randomUUID(),at:new Date().toISOString(),stage});}}/>;
  if(view==="setup")return <ProjectStart t={t} project={project} onEdit={edit} saveStatus={saveStatus} onStage={()=>setView("stage")} onCancel={()=>onDashboard?onDashboard():setView("intro")} onFinish={name=>{edit({name});dispatch({type:"finishProjectSetup",projectId:project.id,at:new Date().toISOString()});goHome();}}/>;
  return <div className={`ri-workspace ${embedded?"ri-embedded":""}`} style={{"--ri-bg":t.bg,"--ri-surface":t.surface,"--ri-ink":t.ink,"--ri-muted":t.inkSoft,"--ri-rule":t.rule,"--ri-accent":t.accent,fontFamily:t.sans}}>
    <style>{`
      .ri-embedded{min-height:0!important}.ri-embedded>.ri-header .ri-brand,.ri-embedded>.ri-header .ri-kicker,.ri-embedded>.ri-header select,.ri-embedded>.ri-header .ri-field{display:none}.ri-embedded>.ri-header{justify-content:flex-end;padding:10px 24px}.ri-embedded .ri-nav{padding:8px 24px}.ri-embedded .ri-main{padding-top:20px}

      .ri-workspace{background:var(--ri-bg);color:var(--ri-ink);min-height:100vh;font-size:14px;line-height:1.5}
      .ri-workspace *{box-sizing:border-box}.ri-workspace button,.ri-workspace input,.ri-workspace select,.ri-workspace textarea{font:inherit}
      .ri-workspace button{cursor:pointer}.ri-workspace button:disabled{opacity:.45;cursor:not-allowed}
      .ri-workspace button:focus-visible,.ri-workspace a:focus-visible{outline:2px solid var(--ri-accent);outline-offset:3px}
      .ri-workspace a{color:var(--ri-ink);text-underline-offset:4px}.ri-header{padding:20px 32px;border-bottom:1px solid var(--ri-rule);display:flex;gap:24px;align-items:center;justify-content:space-between;flex-wrap:wrap}
      .ri-brand{font-size:18px;font-weight:650;letter-spacing:-.5px}.ri-kicker{color:var(--ri-muted);font-size:11px;text-transform:uppercase;letter-spacing:1.5px}
      .ri-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.ri-button{background:transparent;color:var(--ri-ink);border:1px solid var(--ri-rule);border-radius:7px;padding:9px 13px;text-decoration:none;font-size:12px!important}
      .ri-primary{background:var(--ri-accent);color:#0a0a0b;border-color:var(--ri-accent)}
      .ri-layout{display:grid;grid-template-columns:220px minmax(0,1fr);max-width:1600px;margin:auto}.ri-nav{padding:28px 16px;border-right:1px solid var(--ri-rule)}
      .ri-nav button{display:flex;gap:12px;width:100%;text-align:left;padding:15px 10px;background:none;border:0;color:var(--ri-muted);border-radius:8px;margin-bottom:5px}
      .ri-nav button[aria-current=page]{background:var(--ri-surface);color:var(--ri-ink)}.ri-nav small{display:block;font-size:11px;margin-top:3px}.ri-step-num{border:1px solid var(--ri-rule);border-radius:50%;width:25px;height:25px;display:grid;place-items:center;font-size:11px;flex-shrink:0}
      .ri-main{padding:36px;min-width:0}.ri-main h1{font-size:32px;line-height:1.15;letter-spacing:-1px;margin:10px 0 12px;font-weight:550}.ri-main h2{font-size:18px;font-weight:550;margin:0 0 10px}.ri-main p{color:var(--ri-muted);max-width:760px}.ri-lead{font-size:15px;margin:0 0 28px}
      .ri-card{border:1px solid var(--ri-rule);border-radius:12px;padding:24px;margin:20px 0;background:var(--ri-surface)}.ri-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.ri-field{display:flex;flex-direction:column;gap:7px;font-size:12px;color:var(--ri-muted)}
      .ri-workspace input,.ri-workspace select,.ri-workspace textarea{width:100%;padding:11px 12px;border:1px solid var(--ri-rule);border-radius:6px;background:var(--ri-bg);color:var(--ri-ink);min-width:0;color-scheme:dark}.ri-workspace textarea{min-height:100px;resize:vertical}.ri-field small{font-size:11px}.ri-workspace input[type=checkbox]{width:auto}
      .ri-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--ri-rule);border-radius:10px;overflow:hidden;margin:24px 0}.ri-summary>div{padding:16px;border-right:1px solid var(--ri-rule)}.ri-summary span{display:block;font-size:11px;color:var(--ri-muted)}.ri-summary strong{display:block;font-size:18px;font-weight:500;margin-top:6px}
      .ri-table-wrap{overflow:auto}.ri-workspace table{width:100%;border-collapse:collapse;text-align:left;font-size:12px}.ri-workspace th{font-weight:450;color:var(--ri-muted);padding:10px 6px;white-space:nowrap}.ri-workspace td{padding:9px 6px;border-top:1px solid var(--ri-rule)}.ri-unit-table{min-width:770px}.ri-unit-table input{padding:8px;width:90px}.ri-unit-table td:first-child input{width:140px}.ri-unit-table input[type=date]{width:140px}
      .ri-notice{border-left:2px solid var(--ri-accent);padding:10px 16px;background:var(--ri-surface);font-size:12px;color:var(--ri-muted);margin:18px 0}.ri-source{padding:16px 0;border-bottom:1px solid var(--ri-rule)}.ri-source small{display:block;color:var(--ri-muted);margin-top:5px}.ri-footer{display:flex;justify-content:space-between;align-items:center;gap:16px;border-top:1px solid var(--ri-rule);margin-top:32px;padding-top:20px}.ri-error{color:#ffbc9a!important}.ri-import{margin:18px 0}.ri-import summary{cursor:pointer;color:var(--ri-muted);font-size:12px}.ri-save{font-size:11px;color:var(--ri-muted)}.ri-muted{color:var(--ri-muted);font-size:12px}.ri-gap-list{padding-left:20px}.ri-gap-list button{background:none;border:0;text-align:left;color:var(--ri-ink);padding:5px;text-decoration:underline;text-underline-offset:3px}
      .ri-setup-layout{max-width:820px;margin:20px auto}.ri-section-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.ri-section-title p{margin-bottom:0}.ri-next-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:24px}.ri-task{text-align:left;background:var(--ri-bg);color:var(--ri-ink);border:1px solid var(--ri-rule);border-radius:8px;padding:20px}.ri-task:hover{border-color:var(--ri-accent)}.ri-task strong{font-size:14px;font-weight:550;display:block}.ri-task span{display:block;color:var(--ri-muted);font-size:12px;margin-top:10px}.ri-storage{margin-top:26px;color:var(--ri-muted);font-size:11px}.ri-storage summary{cursor:pointer}.ri-card>summary{cursor:pointer;font-size:14px}.ri-workspace .ri-grid>.ri-card{margin:0}
      .ri-market-teasers{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.ri-market-teasers>div{padding:16px;background:var(--ri-bg);border:1px solid var(--ri-rule);border-radius:8px}.ri-market-teasers strong,.ri-market-teasers span,.ri-market-teasers small{display:block}.ri-market-teasers span,.ri-market-teasers small{color:var(--ri-muted);font-size:12px;margin-top:6px}
      @media(max-width:900px){.ri-layout{grid-template-columns:1fr}.ri-nav{display:flex;overflow:auto;border-right:0;border-bottom:1px solid var(--ri-rule);padding:12px}.ri-nav button{min-width:150px;margin:0}.ri-nav small{display:none}.ri-main{padding:24px}.ri-header{padding:16px 24px}.ri-summary{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:560px){.ri-grid,.ri-next-grid,.ri-market-teasers{grid-template-columns:1fr}.ri-main{padding:20px 16px}.ri-card{padding:16px}.ri-main h1{font-size:27px}.ri-header{padding:16px}.ri-footer{align-items:flex-start}.ri-actions{gap:7px}}

      .ri-layout{display:block}.ri-nav{display:flex;gap:6px;border-right:0;border-bottom:1px solid var(--ri-rule);padding:10px 32px;overflow:auto}.ri-nav button{width:auto;min-width:max-content;margin:0;padding:10px 16px}.ri-main{max-width:1180px;margin:auto;padding:40px 36px}.ri-header{padding:18px 32px}.ri-project-hero{display:grid;grid-template-columns:1.5fr 1fr;gap:48px;align-items:center;padding:36px 0 48px;border-bottom:1px solid var(--ri-rule)}.ri-project-hero h2{font-size:36px;font-weight:500;letter-spacing:-1px;line-height:1.16;max-width:520px;margin:22px 0 16px}.ri-project-hero p{max-width:510px;line-height:1.7;color:var(--ri-muted);margin-bottom:28px}.ri-stage-tag{background:var(--ri-surface);border:1px solid var(--ri-rule);color:var(--ri-ink);padding:8px 12px;font-size:12px!important}.ri-building-size{border-left:1px solid var(--ri-rule);padding:20px 40px}.ri-building-size>strong{display:block;font-size:72px;font-weight:400;letter-spacing:-3px;line-height:1.1}.ri-building-size>span{font-size:13px;color:var(--ri-muted)}.ri-building-size small{display:block;color:var(--ri-muted);font-size:12px;margin-top:18px;line-height:1.6}.ri-unit-dots{display:grid;grid-template-columns:repeat(10,1fr);gap:5px;max-width:270px;margin-top:22px}.ri-unit-dots i{aspect-ratio:1;background:var(--ri-surface);border:1px solid var(--ri-rule)}.ri-project-paths{display:grid;grid-template-columns:repeat(3,1fr);border-bottom:1px solid var(--ri-rule)}.ri-project-path{background:none;border:0;border-right:1px solid var(--ri-rule);color:var(--ri-ink);padding:30px 24px;text-align:left}.ri-project-path:first-child{padding-left:0}.ri-project-path:last-child{border-right:0}.ri-project-path>span{color:var(--ri-muted);font-size:11px}.ri-project-path h3{font-size:19px;font-weight:500;margin:18px 0 10px}.ri-project-path p{color:var(--ri-muted);line-height:1.6;font-size:13px;margin:0}.ri-project-path:hover{background:var(--ri-surface)}.ri-project-bottom{display:grid;grid-template-columns:1fr 1fr;gap:40px;padding:24px 0}.ri-project-bottom h3{font-size:14px;font-weight:500}.ri-project-bottom p{color:var(--ri-muted);font-size:12px}.ri-main>.ri-save{margin-bottom:12px}
      @media(max-width:750px){.ri-project-hero{grid-template-columns:1fr;gap:20px}.ri-project-hero h2{font-size:30px}.ri-building-size{border-left:0;border-top:1px solid var(--ri-rule);padding:24px 0}.ri-project-paths,.ri-project-bottom{grid-template-columns:1fr}.ri-project-path{border-right:0;border-bottom:1px solid var(--ri-rule);padding:24px 0}.ri-main{padding:28px 20px}.ri-nav{padding:8px 12px}}
    `}</style>
    <header className="ri-header"><div><div className="ri-brand">LeaseRight</div><div className="ri-kicker">Rhode Island · Pilot workspace</div></div><div className="ri-actions">
      <label className="ri-field"><span className="ri-kicker">Project</span><select aria-label="Switch project" value={project.id} onChange={e=>dispatch({type:"setActiveProject",projectId:e.target.value})}>{state.projects.filter(p=>p.intakeVersion===1).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      {!embedded && <><button className="ri-button" onClick={goHome}>Dashboard</button><button className="ri-button" onClick={newProject}>New project</button></>}<button className="ri-button" onClick={exportProject}>Export backup</button>
      <label className="ri-button" role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter" || e.key===" "){e.preventDefault();e.currentTarget.querySelector("input").click();}}}>Restore backup<input aria-label="Restore project backup" type="file" accept=".json,application/json" onChange={restoreProject} style={{display:"none"}} /></label>
    </div></header>
    <div className={view==="setup"?"ri-setup-layout":"ri-layout"}>
    {view!=="setup" && <nav className="ri-nav" aria-label="Project navigation">
      <button aria-current={view==="home"?"page":undefined} onClick={goHome}>Overview</button>
      {[[0,"Property"],[1,"Unit schedule"],[2,"Comparables"],[3,"Rent assumptions"],[4,"Leasing plan"],[5,"Model & baseline"]].map(([i,label])=><button key={i} aria-current={view==="edit" && step===i?"page":undefined} onClick={()=>openSection(i)}>{label}</button>)}
    </nav>}
    <main className="ri-main"><div className="ri-kicker">{view==="setup"?"New property":project.municipality+" · "+({pre_funding:"Pre-funding",funded_prelaunch:"Pre-launch",active_leaseup:"Lease-up"}[project.stage] || "Planning")}</div>
    <h1>{view==="setup"?"Let’s start your project.":view==="home"?project.name:["Property details","Unit schedule","Comparables & market","Rent assumptions","Leasing plan","Model & baseline"][step]}</h1>
    <p className="ri-lead">{view==="setup"?"Start with the property. Add the details as your plan takes shape.":view==="home"?project.address:["Update the property whenever you learn more.","Add unit types or import a schedule. Rents entered here carry into the model.","Your suggested competition, published prices, and the evidence behind the comparison.","Review concessions and the rents from your unit schedule.","Set timing, pace, and budget when you’re ready to model the lease-up.","Compare the plan and save a baseline when its assumptions are ready."][step]}</p>
    <div className="ri-save" role="status">{saveStatus}</div>
    {message && <div role="alert" className="ri-notice">{message}<button className="ri-button" onClick={()=>setMessage("")} style={{marginLeft:12}}>Dismiss</button></div>}
    {view==="home" && <>
      <section className="ri-project-hero"><div><button className="ri-stage-tag" onClick={()=>setView("stage")}>{focus.label} ↗</button><h2>{focus.title}</h2><p>{focus.detail}</p><button className="ri-button ri-primary" onClick={()=>openSection(focus.section)}>{focus.primary} →</button></div><div className="ri-building-size"><strong>{focus.count || "—"}</strong><span>rental units</span><div className="ri-unit-dots" aria-hidden="true">{Array.from({length:Math.min(focus.count||0,50)},(_,i)=><i key={i} style={knownPosition&&i<leasedCount?{background:"var(--ri-accent)",opacity:.55}:undefined}/>)}</div><small>{knownPosition?`${leasedCount} already leased · ${focus.count-leasedCount} remaining`:d.unitMix.length?`${rowCount} units described in your schedule`:"Your building total is saved. The mix can come later."}</small></div></section>
      <div className="ri-project-paths">{[[1,"01","The building",d.unitMix.length?`${rowCount} units across ${d.unitMix.length} groups.`:"Add a few unit types or import your existing schedule."],[2,"02","The market","Live Providence building records and a limited, dated pricing reference."],[4,"03",project.stage==="active_leaseup"?"The remaining lease-up":"The leasing plan",project.stage==="active_leaseup"?"Plan around units already leased and the ones left to fill.":"Explore timing and costs when you’re ready."]].map(([section,n,title,description])=><button className="ri-project-path" key={n} onClick={()=>openSection(section)}><span>{n} /</span><h3>{title} ↗</h3><p>{description}</p></button>)}</div>
      <section className="ri-project-bottom"><div><h3>{approved?"Approved planning baseline":"Your plan can develop here."}</h3><p>{approved?`${project.baselines.length} saved version${project.baselines.length===1?"":"s"}.`:"Rents, budgets and detailed assumptions are available when you need them."}</p><button className="ri-button" onClick={()=>openSection(5)}>{approved?"View baseline":"Explore the financial model"}</button></div><div><h3>Property details</h3><p>{project.address}</p><button className="ri-button" onClick={()=>openSection(0)}>Edit property</button></div></section>
    </>}
    {view==="edit" && <>
    {step===0 && <>
      <section className="ri-card"><h2>The project brief</h2><div className="ri-grid">{projectField("name","Project name")}{projectField("address","Street address")}{projectField("sponsor","Sponsor / owner (optional)")}
        <IntakeField label="City / town" value={project.municipality} onChange={value=>edit({municipality:value,location:null})} hint="Usually filled from the property address."/>

        <IntakeField label="Project type"><select value={project.developmentType} onChange={e=>edit({developmentType:e.target.value})}><option value="">Choose a project type</option>{["New construction","Conversion / adaptive reuse","Existing rental property"].map(x=><option key={x}>{x}</option>)}</select></IntakeField>
        <div className="ri-field"><span>Project stage</span><button className="ri-button" onClick={()=>setView("stage")}>{focus.label} · Change</button></div>
        {projectField("objective","What decision should this plan support?","For example: establish achievable rents and a leasing budget before financing.")}</div></section>
      <details className="ri-card"><summary>Map & public property records</summary><PropertyLocation t={t} address={project.address} location={project.location} onChange={(address,location)=>edit({address,location,municipality:intakeMunicipality(address,location)},{researchReviewed:false})} /><p className="ri-muted">The town fills from your address. Public parcel records currently cover Providence; missing records do not block your project.</p></details>
    </>}
    {step===1 && <>
      <section className="ri-card"><div className="ri-grid">{field("totalUnits","Total rental units","number")}{field("deliveryDate","Leasing start date","date","A row-specific date below can delay availability for a later phase.")}</div>
      <p className="ri-muted">Schedule: {rowCount} units {d.totalUnits!=="" && ` / project total: ${d.totalUnits}`}</p>
      {!d.unitMix.length && <p className="ri-muted">{d.totalUnits?`Your ${d.totalUnits}-unit building is saved. Group units by bedroom type below; you do not need a row for every apartment.`:"Start with the unit types you know."}</p>}
      <div className="ri-table-wrap"><table className="ri-unit-table" style={{minWidth:unitDetails?770:440}}><thead><tr>{unitColumns.map(key=><th key={key}>{{label:"Unit type",count:"Units",sqft:"Avg. SF",rent:"Monthly rent",leased:"Already leased",availableDate:"Available from"}[key]}</th>)}<th></th></tr></thead><tbody>{d.unitMix.map((row,i)=><tr key={i}>{unitColumns.map(key=><td key={key}><input aria-label={`Row ${i+1} ${key}`} type={key==="label"?"text":key==="availableDate"?"date":"number"} value={row[key]} onChange={e=>changeRow(i,key,e.target.value)} onInput={key==="availableDate"?e=>changeRow(i,key,e.currentTarget.value):undefined} /></td>)}<td><button aria-label={`Remove row ${i+1}`} className="ri-button" onClick={()=>edit({}, {unitMix:d.unitMix.filter((_,n)=>n!==i)})}>Remove</button></td></tr>)}</tbody></table></div>
      <button className="ri-button" disabled={d.unitMix.length>=200} onClick={()=>edit({}, {unitMix:[...d.unitMix,{label:"",count:"",sqft:"",rent:"",leased:project.stage==="active_leaseup"?"":"0",availableDate:""}]})} style={{marginTop:16}}>+ Add unit type</button>
      <button className="ri-button" style={{marginLeft:12}} onClick={()=>setUnitDetails(v=>!v)}>{unitDetails?"Hide extra columns":"Add sizes, leased units & phases"}</button>
      <p className="ri-muted">Already leased is the starting position for planning, not a verified rent roll. This model does not project turnover or lease expirations.</p></section>
      <details className="ri-card ri-import"><summary>Have a unit schedule? Import a CSV</summary><p>Use one row per unit type / phase. The import preview will replace the current schedule only when you apply it. PDF and spreadsheet extraction is not connected yet.</p>
      <button className="ri-button" onClick={()=>download("leaseright-unit-schedule.csv","label,count,sqft,rent,leased,availableDate\n","text/csv")}>Download CSV headers</button>
      <IntakeField label="Unit schedule CSV"><textarea value={csv} onChange={e=>{setCSV(e.target.value);setImportRows(null);}} placeholder="label,count,sqft,rent,leased,availableDate" /></IntakeField>
      <input aria-label="Upload unit schedule CSV" type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;if(f.size>500000){setMessage("Choose a CSV smaller than 500 KB.");return;}setCSV(await f.text());setImportRows(null);}} />
      <button className="ri-button" onClick={()=>{try{setImportRows(parseIntakeCSV(csv));setMessage("");}catch(e){setMessage(e.message);}}}>Preview import</button>
      {importRows && <div><p>{importRows.length} rows · {importRows.reduce((n,r)=>n+(Number(r.count)||0),0)} units. Values will be validated before baseline approval.</p><pre style={{whiteSpace:"pre-wrap"}}>{importRows.map(r=>`${r.label}: ${r.count} units, ${r.sqft} SF, $${r.rent}/month`).join("\n")}</pre><button className="ri-button ri-primary" onClick={()=>{edit({}, {unitMix:importRows});setImportRows(null);setCSV("");setMessage("Unit schedule imported. Review the values and reconcile the project total.");}}>Replace schedule with these rows</button></div>}</details>
    </>}
    {step===2 && <>
      <ComparableMarket project={project} result={market.result} onRefresh={market.refresh} onLocate={()=>openSection(0)} onExclude={(compId,excluded)=>dispatch({type:"setMarketExcluded",projectId:project.id,compId,excluded})} />
      {d.sources.length>0 && <details className="ri-card"><summary>Previously saved sources ({d.sources.length})</summary>{d.sources.map((s,i)=><div className="ri-source" key={s.id||i}>{intakeSafeURL(s.url)?<a href={intakeSafeURL(s.url)} target="_blank" rel="noreferrer">{s.title}</a>:s.title}<p>{s.notes}</p><small>{s.observedOn}</small></div>)}</details>}
    </>}
    {step===3 && <section className="ri-card"><h2>Concessions & lease terms</h2><button className="ri-button" onClick={()=>openSection(1)}>Edit rents in the unit schedule →</button><p>Monthly asking rents are sponsor-entered assumptions. The effective-rent calculation spreads free rent over the lease term and excludes fees and other concessions.</p>
      {!d.unitMix.length && <p>Add your unit schedule in The building first.</p>}
      <div className="ri-grid">{field("leaseTerm","Lease term (months)","number")}{field("freeMonths","Free rent on new leases (months)","number","Enter 0 if no free rent is planned.")}</div>
      <div className="ri-notice">Recorded sources: {d.sources.length}. LeaseRight has not independently verified these rents or calculated a market confidence score.</div></section>}
    {step===4 && <>
      <section className="ri-card"><h2>Timing and execution</h2><div className="ri-grid">{field("deliveryDate","Leasing start date","date")}{field("targetDate","Target stabilization date","date")}{field("targetOccupancy","Target leased occupancy (%)","number","Planning target uses signed leases, not physical move-ins.")}{field("leasesPerWeek","Expected new leases per week","number","Enter your assumption. Slower / faster cases use −20% / +20%.")}
      <IntakeField label="Leasing strategy"><select value={d.strategy} onChange={e=>edit({}, {strategy:e.target.value})}><option value="">Choose an approach</option>{["In-house","Broker-led","Hybrid"].map(x=><option key={x}>{x}</option>)}</select></IntakeField></div></section>
      <section className="ri-card"><h2>Budget assumptions</h2><div className="ri-grid">{field("marketing","Total marketing budget ($)","number")}{field("staffing","Total staffing / brokerage budget ($)","number","Include planned commissions here; they are not calculated separately.")}{field("monthlyCarry","Monthly carrying cost ($)","number","Gross cost of time; this model does not offset it with collected rent.")}</div><IntakeField label="Assumptions, exclusions, and unresolved questions"><textarea value={d.notes} onChange={e=>edit({}, {notes:e.target.value})} /></IntakeField></section>
    </>}
    {step===5 && <>
      <div className="ri-summary"><div><span>Project</span><strong>{project.name}</strong></div><div><span>Municipality</span><strong>{project.municipality || "Unknown"}</strong></div><div><span>Units in schedule</span><strong>{rowCount}</strong></div><div><span>Evidence sources</span><strong>{d.sources.length}</strong></div></div>
      {issues.length>0 ? <section className="ri-card"><h2>The cost model can wait.</h2><p>Your property and market comparisons are available now. To calculate a detailed lease-up scenario, add the remaining assumptions when you have them.</p><div className="ri-actions">{[...new Set(issues.map(x=>x.step))].map(i=><button className="ri-button" key={i} onClick={()=>openSection(i)}>{["Property details","Unit mix & rents","Market context","Concessions & term","Timing & budget","Model"][i]}</button>)}</div><details style={{marginTop:20}}><summary>See missing or inconsistent assumptions</summary><ul>{issues.map((x,i)=><li key={i}>{x.message}</li>)}</ul></details></section> : <>
      <section className="ri-card"><h2>Calculated project summary</h2><div className="ri-summary"><div><span>Weighted asking rent</span><strong>{intakeMoney(output.averageRent)}</strong></div><div><span>Effective monthly rent</span><strong>{intakeMoney(output.effectiveRent)}</strong></div><div><span>Gross rent / month at 100%</span><strong>{intakeMoney(output.grossMonthlyRent)}</strong></div><div><span>Required average leasing pace</span><strong>{output.requiredLeasesPerWeek.toFixed(2)} / week</strong></div></div><p>{output.existingLeased} already leased → {output.targetLeased} target leased units. Required pace is averaged across the whole target window; later delivery phases can make that pace insufficient.</p></section>
      <section className="ri-card"><h2>Leasing pace sensitivities</h2><p>Calculated illustrations, not market forecasts. All cases use the same rents, concessions, and fixed budgets; only weekly leasing pace changes.</p><div className="ri-table-wrap"><table><thead><tr>{["Case","Leases / week","Stabilization","Free rent","Gross carry","Total plan cost"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{output.scenarios.map(s=><tr key={s.name}><td>{s.name}<small style={{display:"block"}}>{s.meetsTarget?"Meets target":"Misses target"}</small></td><td>{s.leasesPerWeek.toFixed(2)}</td><td>{s.stabilizeDate || "Beyond 10 years"}</td><td>{intakeMoney(s.concessionCost)}</td><td>{intakeMoney(s.carryCost)}</td><td>{s.stabilizeDate?intakeMoney(s.totalCost):"Incomplete horizon"}</td></tr>)}</tbody></table></div><p className="ri-muted">Availability-constrained daily approximation; leasing capacity is allocated in unit-row order. Carry = monthly cost × elapsed days ÷ 30.4375. Total plan cost includes free rent, gross carry, and entered marketing and staffing budgets. This is not NOI, a cash-flow forecast, or a valuation.</p></section>
      {!d.sources.length && <div className="ri-notice">No market evidence recorded. An approved version will retain this limitation.</div>}
      {!output.scenarios[1]?.stabilizeDate && <div className="ri-notice">The base case does not stabilize within ten years. Revise the availability or pace before approval.</div>}
      {approved ? <section className="ri-card"><h2>Baseline approved</h2><p>Version {project.baselines.length} · {new Date(approved.approvedAt).toLocaleString()}. Editing the project creates a new draft; this snapshot remains in its history.</p><p>Project unit types and the planning baseline are established. Tenant records, a live leasing board, and reporting integrations are not connected yet.</p></section> : <button className="ri-button ri-primary" disabled={!output.scenarios[1]?.stabilizeDate} onClick={()=>{dispatch({type:"approveIntakeBaseline",projectId:project.id,id:crypto.randomUUID(),at:new Date().toISOString()});goHome();}}>Approve baseline & open project →</button>}
      </>}
      {project.baselines.length>0 && <details className="ri-card"><summary>Approved version history ({project.baselines.length})</summary>{project.baselines.map((b,i)=><div key={b.id} className="ri-source">Version {i+1} · {new Date(b.approvedAt).toLocaleString()} · {b.output.totalUnits} units<button className="ri-button" style={{marginLeft:12}} onClick={()=>download(`leaseright-baseline-${i+1}.json`,JSON.stringify(b,null,2),"application/json")}>Export snapshot</button></div>)}</details>}
    </>}
    <footer className="ri-footer"><span className="ri-muted">Changes save automatically.</span><button className="ri-button ri-primary" onClick={goHome}>Done · back to dashboard →</button></footer>
    </>}
    <details className="ri-storage"><summary>Saved on this device</summary><p>Drafts are stored in this browser, not synced to an account. Use Export backup to keep a separate copy.</p></details>
    </main></div>
  </div>;
}
Object.assign(window,{IntakeWorkspace});
