/* global React, PropertyLocation, RI_TOWNS, intakeIssues, calculateIntake, parseIntakeCSV, intakeSafeURL */
const INTAKE_STEPS = [
  ["The project","Place, purpose & ownership"], ["The building","Unit schedule & delivery"],
  ["The evidence","Public records & market research"], ["The rents","Pricing & concessions"],
  ["The plan","Timing, budget & execution"], ["Review","Scenarios & approved baseline"]
];
const intakeMoney = value => value == null ? "—" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
function IntakeField({label,value,onChange,type="text",children,hint,...rest}) {
  return <label className="ri-field"><span>{label}</span>{children || <input type={type} value={value ?? ""} onChange={e=>onChange(e.target.value)} onInput={type==="date" ? e=>onChange(e.currentTarget.value) : undefined} {...rest} />}{hint && <small>{hint}</small>}</label>;
}
function IntakeWorkspace({t,project}) {
  const {state,dispatch,saveStatus} = useStore();
  const d=project.draft, step=d.step, issues=intakeIssues(project), output=calculateIntake(project);
  const [csv,setCSV]=React.useState(""), [importRows,setImportRows]=React.useState(null), [message,setMessage]=React.useState("");
  React.useEffect(()=>{window.scrollTo({top:0,behavior:"instant"});},[step,project.id]);
  const [source,setSource]=React.useState({title:"",url:"",observedOn:"",notes:""});
  const edit=(patch={},draft={},navigationOnly=false)=>dispatch({type:"editIntakeProject",projectId:project.id,patch,draft,navigationOnly,at:new Date().toISOString()});
  const field=(key,label,type="text",hint)=> <IntakeField label={label} type={type} value={d[key]} onChange={value=>edit({}, {[key]:value})} hint={hint} />;
  const projectField=(key,label,hint)=> <IntakeField label={label} value={project[key]} onChange={value=>edit({[key]:value})} hint={hint} />;
  const changeRow=(index,key,value)=>edit({}, {unitMix:d.unitMix.map((r,i)=>i===index?{...r,[key]:value}:r)});
  const newProject=()=>dispatch({type:"createIntakeProject",id:"ri-"+crypto.randomUUID(),at:new Date().toISOString(),stage:"pre_funding"});
  const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const exportProject=()=>download((project.name || "LeaseRight")+".json",JSON.stringify({format:"leaseright-project",version:1,project},null,2),"application/json");
  const restoreProject=async event=>{
    const file=event.target.files?.[0];event.target.value="";if(!file)return;
    try {
      if(file.size>5000000)throw new Error("Choose a project backup smaller than 5 MB.");
      const saved=JSON.parse(await file.text());
      if(saved.format!=="leaseright-project" || saved.version!==1 || !validIntakeDraft(saved.project))throw new Error("Choose a LeaseRight project backup exported from this intake.");
      const id="ri-"+crypto.randomUUID();
      dispatch({type:"createIntakeProject",id,stage:saved.project.stage,at:new Date().toISOString()});
      const p=saved.project;
      // Import only project-owned fields; approval must be reviewed again in the new project.
      dispatch({type:"editIntakeProject",projectId:id,patch:{name:p.name,address:p.address,sponsor:p.sponsor,municipality:p.municipality,objective:p.objective,developmentType:p.developmentType,location:null,baselines:p.baselines},draft:p.draft,at:new Date().toISOString()});
    }catch(error){setMessage(error.message);}
  };
  const addSource=()=>{
    if(!source.title.trim() || !intakeSafeURL(source.url) || intakeDate(source.observedOn)===null || source.observedOn>new Date().toISOString().slice(0,10)){setMessage("Add a source title, an http(s) link, and a valid observation date that is not in the future.");return;}
    edit({}, {sources:[...d.sources,{...source,id:crypto.randomUUID(),recordedAt:new Date().toISOString(),origin:"User-recorded observation"}],researchReviewed:false});setSource({title:"",url:"",observedOn:"",notes:""});setMessage("");
  };
  const rowCount=d.unitMix.reduce((sum,r)=>sum+(Number(r.count)||0),0);
  const approved=project.baselines.find(b=>b.id===project.approvedBaselineId);
  return <div className="ri-workspace" style={{"--ri-bg":t.bg,"--ri-surface":t.surface,"--ri-ink":t.ink,"--ri-muted":t.inkSoft,"--ri-rule":t.rule,"--ri-accent":t.accent,fontFamily:t.sans}}>
    <style>{`
      .ri-workspace{background:var(--ri-bg);color:var(--ri-ink);min-height:100vh;font-size:14px;line-height:1.5}
      .ri-workspace *{box-sizing:border-box}.ri-workspace button,.ri-workspace input,.ri-workspace select,.ri-workspace textarea{font:inherit}
      .ri-workspace button{cursor:pointer}.ri-workspace button:disabled{opacity:.45;cursor:not-allowed}
      .ri-workspace button:focus-visible,.ri-workspace a:focus-visible{outline:2px solid var(--ri-accent);outline-offset:3px}
      .ri-workspace a{color:var(--ri-ink);text-underline-offset:4px}.ri-header{padding:20px 32px;border-bottom:1px solid var(--ri-rule);display:flex;gap:24px;align-items:center;justify-content:space-between;flex-wrap:wrap}
      .ri-brand{font-size:18px;font-weight:650;letter-spacing:-.5px}.ri-kicker{color:var(--ri-muted);font-size:11px;text-transform:uppercase;letter-spacing:1.5px}
      .ri-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.ri-button{background:transparent;color:var(--ri-ink);border:1px solid var(--ri-rule);border-radius:7px;padding:9px 13px;text-decoration:none;font-size:12px!important}
      .ri-primary{background:var(--ri-ink);color:var(--ri-bg);border-color:var(--ri-ink)}
      .ri-layout{display:grid;grid-template-columns:220px minmax(0,1fr);max-width:1600px;margin:auto}.ri-nav{padding:28px 16px;border-right:1px solid var(--ri-rule)}
      .ri-nav button{display:flex;gap:12px;width:100%;text-align:left;padding:15px 10px;background:none;border:0;color:var(--ri-muted);border-radius:8px;margin-bottom:5px}
      .ri-nav button[aria-current=step]{background:var(--ri-surface);color:var(--ri-ink)}.ri-nav small{display:block;font-size:11px;margin-top:3px}.ri-step-num{border:1px solid var(--ri-rule);border-radius:50%;width:25px;height:25px;display:grid;place-items:center;font-size:11px;flex-shrink:0}
      .ri-main{padding:36px;min-width:0}.ri-main h1{font-size:32px;line-height:1.15;letter-spacing:-1px;margin:10px 0 12px;font-weight:550}.ri-main h2{font-size:18px;font-weight:550;margin:0 0 10px}.ri-main p{color:var(--ri-muted);max-width:760px}.ri-lead{font-size:15px;margin:0 0 28px}
      .ri-card{border:1px solid var(--ri-rule);border-radius:12px;padding:24px;margin:20px 0;background:var(--ri-surface)}.ri-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.ri-field{display:flex;flex-direction:column;gap:7px;font-size:12px;color:var(--ri-muted)}
      .ri-workspace input,.ri-workspace select,.ri-workspace textarea{width:100%;padding:11px 12px;border:1px solid var(--ri-rule);border-radius:6px;background:var(--ri-bg);color:var(--ri-ink);min-width:0;color-scheme:dark}.ri-workspace textarea{min-height:100px;resize:vertical}.ri-field small{font-size:11px}.ri-workspace input[type=checkbox]{width:auto}
      .ri-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--ri-rule);border-radius:10px;overflow:hidden;margin:24px 0}.ri-summary>div{padding:16px;border-right:1px solid var(--ri-rule)}.ri-summary span{display:block;font-size:11px;color:var(--ri-muted)}.ri-summary strong{display:block;font-size:18px;font-weight:500;margin-top:6px}
      .ri-table-wrap{overflow:auto}.ri-workspace table{width:100%;border-collapse:collapse;text-align:left;font-size:12px}.ri-workspace th{font-weight:450;color:var(--ri-muted);padding:10px 6px;white-space:nowrap}.ri-workspace td{padding:9px 6px;border-top:1px solid var(--ri-rule)}.ri-unit-table{min-width:770px}.ri-unit-table input{padding:8px;width:90px}.ri-unit-table td:first-child input{width:140px}.ri-unit-table input[type=date]{width:140px}
      .ri-notice{border-left:2px solid var(--ri-accent);padding:10px 16px;background:var(--ri-surface);font-size:12px;color:var(--ri-muted);margin:18px 0}.ri-source{padding:16px 0;border-bottom:1px solid var(--ri-rule)}.ri-source small{display:block;color:var(--ri-muted);margin-top:5px}.ri-footer{display:flex;justify-content:space-between;align-items:center;gap:16px;border-top:1px solid var(--ri-rule);margin-top:32px;padding-top:20px}.ri-error{color:#ffbc9a!important}.ri-import{margin:18px 0}.ri-import summary{cursor:pointer;color:var(--ri-muted);font-size:12px}.ri-save{font-size:11px;color:var(--ri-muted)}.ri-muted{color:var(--ri-muted);font-size:12px}.ri-gap-list{padding-left:20px}.ri-gap-list button{background:none;border:0;text-align:left;color:var(--ri-ink);padding:5px;text-decoration:underline;text-underline-offset:3px}
      @media(max-width:900px){.ri-layout{grid-template-columns:1fr}.ri-nav{display:flex;overflow:auto;border-right:0;border-bottom:1px solid var(--ri-rule);padding:12px}.ri-nav button{min-width:150px;margin:0}.ri-nav small{display:none}.ri-main{padding:24px}.ri-header{padding:16px 24px}.ri-summary{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:560px){.ri-grid{grid-template-columns:1fr}.ri-main{padding:20px 16px}.ri-card{padding:16px}.ri-main h1{font-size:27px}.ri-header{padding:16px}.ri-footer{align-items:flex-start}.ri-actions{gap:7px}}
    `}</style>
    <header className="ri-header"><div><div className="ri-brand">LeaseRight</div><div className="ri-kicker">Rhode Island · Pilot workspace</div></div><div className="ri-actions">
      <label className="ri-field"><span className="ri-kicker">Project</span><select aria-label="Switch project" value={project.id} onChange={e=>dispatch({type:"setActiveProject",projectId:e.target.value})}>{state.projects.filter(p=>p.intakeVersion===1).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <button className="ri-button" onClick={newProject}>New project</button><button className="ri-button" onClick={exportProject}>Export backup</button>
      <label className="ri-button" role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter" || e.key===" "){e.preventDefault();e.currentTarget.querySelector("input").click();}}}>Restore backup<input aria-label="Restore project backup" type="file" accept=".json,application/json" onChange={restoreProject} style={{display:"none"}} /></label>
    </div></header>
    <div className="ri-layout"><nav className="ri-nav" aria-label="Intake steps">{INTAKE_STEPS.map(([title,sub],i)=><button key={title} aria-current={step===i?"step":undefined} onClick={()=>edit({}, {step:i},true)}><span className="ri-step-num">{i+1}</span><span>{title}<small>{sub}</small></span></button>)}</nav>
    <main className="ri-main"><div className="ri-kicker">Project intake / {String(step+1).padStart(2,"0")}</div><h1>{["Start with what you know.","Define what you’re delivering.","Build a record you can trust.","Make the rent assumptions explicit.","Give the project a path to lease-up.","A plan built from your inputs."][step]}</h1>
    <p className="ri-lead">{["A site is the starting point. Tell us what you’re planning and what this project needs to decide.","One row per unit type and delivery phase. Existing building records stay separate from your proposed program.","Review municipal records and record the sources supporting your plan. Missing information stays visible.","These are sponsor assumptions until supported by evidence. Change them here and the scenarios will recalculate.","Set the goal, the execution approach, and the cost of time. You can leave unknowns blank while drafting.","Review the gaps, compare the calculated sensitivities, and save an approved version when you’re ready."][step]}</p>
    <div className="ri-save" role="status">{saveStatus} · Browser drafts are not synced to an account. Export a backup to keep a separate copy.</div>
    {message && <div role="alert" className="ri-notice">{message}<button className="ri-button" onClick={()=>setMessage("")} style={{marginLeft:12}}>Dismiss</button></div>}
    {step===0 && <>
      <section className="ri-card"><h2>The project brief</h2><div className="ri-grid">{projectField("name","Project name")}{projectField("sponsor","Sponsor / owner")}
        <IntakeField label="Municipality"><select value={project.municipality} onChange={e=>edit({municipality:e.target.value,location:null},{researchReviewed:false})}><option value="">Choose a Rhode Island city or town</option>{RI_TOWNS.map(name=><option key={name}>{name}</option>)}</select></IntakeField>
        <IntakeField label="Project type"><select value={project.developmentType} onChange={e=>edit({developmentType:e.target.value})}><option value="">Choose a project type</option>{["New construction","Conversion / adaptive reuse","Existing rental property"].map(x=><option key={x}>{x}</option>)}</select></IntakeField>
        <IntakeField label="Project stage"><select value={project.stage} onChange={e=>edit({stage:e.target.value})}><option value="pre_funding">Pre-funding</option><option value="funded_prelaunch">Funded · pre-launch</option><option value="active_leaseup">Active lease-up</option></select></IntakeField>
        {projectField("objective","What decision should this plan support?","For example: establish achievable rents and a leasing budget before financing.")}</div></section>
      <section className="ri-card"><h2>Locate the property</h2><PropertyLocation t={t} address={project.address} location={project.location} onChange={(address,location)=>edit({address,location},{researchReviewed:false})} /><p className="ri-muted">Confirm the municipality above separately from the mailing address. The current automatic parcel connector covers Providence; other municipalities use manual research for now.</p></section>
    </>}
    {step===1 && <>
      <section className="ri-card"><div className="ri-grid">{field("totalUnits","Total proposed / existing rental units","number")}{field("deliveryDate","Leasing start date","date","A row-specific date below can delay availability for a later phase.")}</div>
      <p className={rowCount!==+d.totalUnits?"ri-error":"ri-muted"}>Schedule: {rowCount} units {d.totalUnits!=="" && ` / project total: ${d.totalUnits}`}</p>
      <div className="ri-table-wrap"><table className="ri-unit-table"><thead><tr>{["Type / phase","Units","Avg. SF","Monthly rent","Already leased","Available from",""].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{d.unitMix.map((row,i)=><tr key={i}>{["label","count","sqft","rent","leased","availableDate"].map(key=><td key={key}><input aria-label={`Row ${i+1} ${key}`} type={key==="label"?"text":key==="availableDate"?"date":"number"} value={row[key]} onChange={e=>changeRow(i,key,e.target.value)} onInput={key==="availableDate"?e=>changeRow(i,key,e.currentTarget.value):undefined} /></td>)}<td><button aria-label={`Remove row ${i+1}`} className="ri-button" onClick={()=>edit({}, {unitMix:d.unitMix.filter((_,n)=>n!==i)})}>Remove</button></td></tr>)}</tbody></table></div>
      <button className="ri-button" disabled={d.unitMix.length>=200} onClick={()=>edit({}, {unitMix:[...d.unitMix,{label:"",count:"",sqft:"",rent:"",leased:"0",availableDate:""}]})} style={{marginTop:16}}>+ Add unit type / phase</button>
      <p className="ri-muted">Already leased is the starting position for planning, not a verified rent roll. This model does not project turnover or lease expirations.</p></section>
      <details className="ri-card ri-import"><summary>Have a unit schedule? Import a CSV</summary><p>Use one row per unit type / phase. The import preview will replace the current schedule only when you apply it. PDF and spreadsheet extraction is not connected yet.</p>
      <button className="ri-button" onClick={()=>download("leaseright-unit-schedule.csv","label,count,sqft,rent,leased,availableDate\n","text/csv")}>Download CSV headers</button>
      <IntakeField label="Unit schedule CSV"><textarea value={csv} onChange={e=>{setCSV(e.target.value);setImportRows(null);}} placeholder="label,count,sqft,rent,leased,availableDate" /></IntakeField>
      <input aria-label="Upload unit schedule CSV" type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;if(f.size>500000){setMessage("Choose a CSV smaller than 500 KB.");return;}setCSV(await f.text());setImportRows(null);}} />
      <button className="ri-button" onClick={()=>{try{setImportRows(parseIntakeCSV(csv));setMessage("");}catch(e){setMessage(e.message);}}}>Preview import</button>
      {importRows && <div><p>{importRows.length} rows · {importRows.reduce((n,r)=>n+(Number(r.count)||0),0)} units. Values will be validated before baseline approval.</p><pre style={{whiteSpace:"pre-wrap"}}>{importRows.map(r=>`${r.label}: ${r.count} units, ${r.sqft} SF, $${r.rent}/month`).join("\n")}</pre><button className="ri-button ri-primary" onClick={()=>{edit({}, {unitMix:importRows});setImportRows(null);setCSV("");setMessage("Unit schedule imported. Review the values and reconcile the project total.");}}>Replace schedule with these rows</button></div>}</details>
    </>}
    {step===2 && <>
      <section className="ri-card"><h2>{project.municipality || "Rhode Island"} research coverage</h2><p>Providence parcel and zoning lookup is connected in the property step. The links below are research starting points, not completed searches.</p>
      <div className="ri-source"><strong>Parcel / zoning record</strong><small>{project.location?.gis?.confirmed ? `Confirmed parcel ${project.location.gis.parcel.id}. Retrieved ${project.location.gis.retrievedAt || "date not recorded"}. Review full details in The project.` : "No municipal parcel record confirmed for this project."}</small><a href="https://www.ri.gov/towns/" target="_blank" rel="noreferrer">Official Rhode Island municipal directory ↗</a></div>
      {project.municipality==="Providence" && <><div className="ri-source"><a href="https://www.providenceri.gov/inspection/online-permitting/" target="_blank" rel="noreferrer">Providence permits ↗</a><small>Manual review · permits do not establish delivery timing.</small></div><div className="ri-source"><a href="https://www.providenceri.gov/providence-development-projects/" target="_blank" rel="noreferrer">Providence development pipeline ↗</a><small>Manual review · record the relevant projects and observation dates.</small></div></>}
      <div className="ri-source"><a href="https://planning.ri.gov/planning-areas/data-center/ri-data-center-census-data/census-2020" target="_blank" rel="noreferrer">Rhode Island Census data resources ↗</a><small>Neighborhood context · not a building-specific rent estimate.</small></div>
      <div className="ri-source"><strong>Rental comparables</strong><small>No live listing feed connected. Record property-site links, unit sizes, asking rents, concessions, and observation dates below. Advertised availability is not verified occupancy.</small></div></section>
      <section className="ri-card"><h2>Evidence register</h2><p>Add sources you have reviewed. These notes support human review; they do not silently overwrite project assumptions.</p>
      {!d.sources.length && <div className="ri-notice">No market or document sources recorded yet. Your rent plan is currently unsupported by recorded market evidence.</div>}
      {d.sources.map((s,i)=><div className="ri-source" key={s.id || i}>{intakeSafeURL(s.url)?<a href={intakeSafeURL(s.url)} target="_blank" rel="noreferrer">{s.title} ↗</a>:<strong>{s.title}</strong>}<small>Observed {s.observedOn} · User-recorded observation</small><p>{s.notes}</p><button className="ri-button" onClick={()=>edit({}, {sources:d.sources.filter((_,n)=>n!==i),researchReviewed:false})}>Remove source</button></div>)}
      <div className="ri-grid" style={{marginTop:20}}>{[["title","Source / property name","text"],["url","Source URL","url"],["observedOn","Date observed","date"]].map(([key,label,type])=><IntakeField key={key} label={label} type={type} value={source[key]} onChange={value=>setSource(s=>({...s,[key]:value}))} />)}<IntakeField label="What does this source tell us?"><textarea value={source.notes} onChange={e=>setSource(s=>({...s,notes:e.target.value}))} placeholder="Record facts, limitations, and any conflict with the sponsor’s plan." /></IntakeField></div><button className="ri-button" onClick={addSource} style={{marginTop:16}}>Add reviewed source</button></section>
      <label className="ri-notice" style={{display:"block"}}><input type="checkbox" checked={!!d.researchReviewed} onChange={e=>edit({}, {researchReviewed:e.target.checked})} /> I have reviewed the available research and understand that unverified assumptions still require diligence.</label>
    </>}
    {step===3 && <section className="ri-card"><h2>Rent by unit type</h2><p>Monthly asking rents are sponsor-entered assumptions. The effective-rent calculation spreads free rent over the lease term and excludes fees and other concessions.</p>
      {!d.unitMix.length && <p>Add your unit schedule in The building first.</p>}
      <div className="ri-grid">{d.unitMix.map((r,i)=><IntakeField key={i} label={`${r.label || `Row ${i+1}`} · ${r.count || "?"} units · monthly rent`} type="number" value={r.rent} onChange={value=>changeRow(i,"rent",value)} />)}{field("leaseTerm","Lease term (months)","number")}{field("freeMonths","Free rent on new leases (months)","number","Enter 0 if no free rent is planned.")}</div>
      <div className="ri-notice">Recorded sources: {d.sources.length}. LeaseRight has not independently verified these rents or calculated a market confidence score.</div></section>}
    {step===4 && <>
      <section className="ri-card"><h2>Timing and execution</h2><div className="ri-grid">{field("deliveryDate","Leasing start date","date")}{field("targetDate","Target stabilization date","date")}{field("targetOccupancy","Target leased occupancy (%)","number","Planning target uses signed leases, not physical move-ins.")}{field("leasesPerWeek","Expected new leases per week","number","Enter your assumption. Slower / faster cases use −20% / +20%.")}
      <IntakeField label="Leasing strategy"><select value={d.strategy} onChange={e=>edit({}, {strategy:e.target.value})}><option value="">Choose an approach</option>{["In-house","Broker-led","Hybrid"].map(x=><option key={x}>{x}</option>)}</select></IntakeField></div></section>
      <section className="ri-card"><h2>Budget assumptions</h2><div className="ri-grid">{field("marketing","Total marketing budget ($)","number")}{field("staffing","Total staffing / brokerage budget ($)","number","Include planned commissions here; they are not calculated separately.")}{field("monthlyCarry","Monthly carrying cost ($)","number","Gross cost of time; this model does not offset it with collected rent.")}</div><IntakeField label="Assumptions, exclusions, and unresolved questions"><textarea value={d.notes} onChange={e=>edit({}, {notes:e.target.value})} /></IntakeField></section>
    </>}
    {step===5 && <>
      <div className="ri-summary"><div><span>Project</span><strong>{project.name}</strong></div><div><span>Municipality</span><strong>{project.municipality || "Unknown"}</strong></div><div><span>Units in schedule</span><strong>{rowCount}</strong></div><div><span>Evidence sources</span><strong>{d.sources.length}</strong></div></div>
      {issues.length>0 ? <section className="ri-card"><h2>{issues.length} items to resolve before approval</h2><p>Your draft is saved even when incomplete. Select an item to return to its section.</p><ul className="ri-gap-list">{issues.map((issue,i)=><li key={i}><button onClick={()=>edit({}, {step:issue.step},true)}>{issue.message}</button></li>)}</ul></section> : <>
      <section className="ri-card"><h2>Calculated project summary</h2><div className="ri-summary"><div><span>Weighted asking rent</span><strong>{intakeMoney(output.averageRent)}</strong></div><div><span>Effective monthly rent</span><strong>{intakeMoney(output.effectiveRent)}</strong></div><div><span>Gross rent / month at 100%</span><strong>{intakeMoney(output.grossMonthlyRent)}</strong></div><div><span>Required average leasing pace</span><strong>{output.requiredLeasesPerWeek.toFixed(2)} / week</strong></div></div><p>{output.existingLeased} already leased → {output.targetLeased} target leased units. Required pace is averaged across the whole target window; later delivery phases can make that pace insufficient.</p></section>
      <section className="ri-card"><h2>Leasing pace sensitivities</h2><p>Calculated illustrations, not market forecasts. All cases use the same rents, concessions, and fixed budgets; only weekly leasing pace changes.</p><div className="ri-table-wrap"><table><thead><tr>{["Case","Leases / week","Stabilization","Free rent","Gross carry","Total plan cost"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{output.scenarios.map(s=><tr key={s.name}><td>{s.name}<small style={{display:"block"}}>{s.meetsTarget?"Meets target":"Misses target"}</small></td><td>{s.leasesPerWeek.toFixed(2)}</td><td>{s.stabilizeDate || "Beyond 10 years"}</td><td>{intakeMoney(s.concessionCost)}</td><td>{intakeMoney(s.carryCost)}</td><td>{s.stabilizeDate?intakeMoney(s.totalCost):"Incomplete horizon"}</td></tr>)}</tbody></table></div><p className="ri-muted">Availability-constrained daily approximation; leasing capacity is allocated in unit-row order. Carry = monthly cost × elapsed days ÷ 30.4375. Total plan cost includes free rent, gross carry, and entered marketing and staffing budgets. This is not NOI, a cash-flow forecast, or a valuation.</p></section>
      {!d.sources.length && <div className="ri-notice">No market evidence recorded. An approved version will retain this limitation.</div>}
      {!output.scenarios[1]?.stabilizeDate && <div className="ri-notice">The base case does not stabilize within ten years. Revise the availability or pace before approval.</div>}
      {approved ? <section className="ri-card"><h2>Baseline approved</h2><p>Version {project.baselines.length} · {new Date(approved.approvedAt).toLocaleString()}. Editing the project creates a new draft; this snapshot remains in its history.</p><p>Project unit types and the planning baseline are established. Tenant records, a live leasing board, and reporting integrations are not connected yet.</p></section> : <button className="ri-button ri-primary" disabled={!output.scenarios[1]?.stabilizeDate} onClick={()=>dispatch({type:"approveIntakeBaseline",projectId:project.id,id:crypto.randomUUID(),at:new Date().toISOString()})}>Approve base plan · save version {project.baselines.length+1}</button>}
      </>}
      {project.baselines.length>0 && <details className="ri-card"><summary>Approved version history ({project.baselines.length})</summary>{project.baselines.map((b,i)=><div key={b.id} className="ri-source">Version {i+1} · {new Date(b.approvedAt).toLocaleString()} · {b.output.totalUnits} units<button className="ri-button" style={{marginLeft:12}} onClick={()=>download(`leaseright-baseline-${i+1}.json`,JSON.stringify(b,null,2),"application/json")}>Export snapshot</button></div>)}</details>}
    </>}
    <footer className="ri-footer"><button className="ri-button" disabled={step===0} onClick={()=>edit({}, {step:step-1},true)}>← Back</button><div className="ri-actions"><span className="ri-muted">{issues.filter(x=>x.step===step).length} open items in this section</span>{step<5 && <button className="ri-button ri-primary" onClick={()=>edit({}, {step:step+1},true)}>Continue →</button>}</div></footer>
    </main></div>
  </div>;
}
Object.assign(window,{IntakeWorkspace});
