/* Saved-property dashboard. Sample operational records never enter this surface. */
function ProjectDashboard({t,project,onNavigate,onSetup}) {
  const f=projectDashboardFacts(project),focus=intakeProjectFocus(project);
  const action=(label,fn)=><button onClick={fn} style={{padding:'10px 15px',background:t.surface,border:`1px solid ${t.rule}`,color:t.ink,cursor:'pointer',fontFamily:t.sans,borderRadius:3}}>{label}</button>;
  return <main className="lr-dashboard" style={{maxWidth:1320,margin:'auto',padding:'36px 32px',fontFamily:t.sans}}>
    <style>{`.lr-dash-metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid ${t.rule};margin:28px 0}.lr-dash-metrics>div{padding:22px;border-right:1px solid ${t.rule}}.lr-dash-metrics>div:last-child{border-right:0}.lr-dash-columns{display:grid;grid-template-columns:1.4fr 1fr;gap:22px}.lr-dash-panel{border:1px solid ${t.rule};background:${t.surface};padding:24px}.lr-dash-panel h2{font-size:16px;font-weight:550;margin:0 0 18px}.lr-dash-panel p{font-size:13px;line-height:1.7;color:${t.inkSoft}}.lr-dash-actions{display:flex;gap:10px;flex-wrap:wrap}@media(max-width:750px){.lr-dash-metrics{grid-template-columns:1fr 1fr}.lr-dash-columns{grid-template-columns:1fr}.lr-dashboard{padding:24px 16px!important}}`}</style>
    <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontFamily:t.mono,fontSize:11,color:t.inkMute,marginBottom:12}}>TODAY / {focus.label.toUpperCase()}</div><h1 style={{fontSize:30,fontWeight:550,letterSpacing:-1,margin:0}}>{project.name==='Untitled project'?'Your property':project.name}</h1><p style={{color:t.inkSoft,fontSize:13}}>{project.address||'Property address not added yet'}</p></div>{action('Edit property',onSetup)}</div>
    <section className="lr-dash-metrics" aria-label="Property summary">{[['TOTAL UNITS',f.total],['ALREADY LEASED',f.leased],['REMAINING',f.remaining],['LEASED SHARE',f.occupancy===null?null:f.occupancy.toFixed(0)+'%']].map(([label,value])=><div key={label}><div style={{fontFamily:t.mono,fontSize:10,color:t.inkMute,letterSpacing:1}}>{label}</div><strong style={{fontFamily:t.mono,fontSize:32,fontWeight:450,display:'block',marginTop:14}}>{value??'—'}</strong><small style={{fontSize:11,color:t.inkMute}}>{value===null?'Not entered':label==='TOTAL UNITS'?'From property details':'From your saved unit schedule'}</small></div>)}</section>
    <div className="lr-dash-columns"><section className="lr-dash-panel"><h2>Leasing position</h2>{f.leased===null?<p>Add your unit mix and already-leased counts when ready. The dashboard is available while those details are incomplete.</p>:<><div style={{display:'flex',height:12,background:t.rule,margin:'24px 0 14px'}}><div style={{width:f.occupancy+'%',background:t.accent}}/></div><p><strong style={{color:t.ink}}>{f.leased} of {f.total} units leased</strong> · {f.remaining} remaining. This is your saved planning position; live leases and turnover are not connected.</p></>}<div className="lr-dash-actions">{action('Open unit schedule',()=>onNavigate('units'))}{action('View leasing model',()=>onNavigate('model'))}</div></section>
    <section className="lr-dash-panel"><h2>Project workspace</h2><p>{focus.detail}</p><div className="lr-dash-actions">{action('Market research',()=>onNavigate('market'))}{action('Rent assumptions',()=>onNavigate('rents'))}</div><p>{project.baselines.length?`${project.baselines.length} saved planning baseline(s).`:'Financial assumptions are optional until you want to calculate a leasing plan.'}</p></section>
    <section className="lr-dash-panel"><h2>Pipeline & activity</h2><p>Lead tracking and leasing activity are not connected for this property yet.</p>{action('Open pipeline',()=>onNavigate('pipeline'))}</section><section className="lr-dash-panel"><h2>Property record</h2><p>{project.municipality||'Town not set'}{project.municipality?', Rhode Island':''} · {focus.label}</p><p>Changes save in this browser. Export a backup from Property details to keep a separate copy.</p>{action('Property details & backup',()=>onNavigate('property'))}</section></div>
  </main>;
}
function ProjectModuleEmpty({t,tab,onNavigate}) {
  const names={pipeline:'Pipeline',inbox:'Inbox',applications:'Applications',lp:'Reports',residents:'Residents',collection:'Collection',maintenance:'Maintenance',ledger:'Ledger',listings:'Listings',vendors:'Vendors',documents:'Documents',settings:'Settings'};
  return <main style={{maxWidth:1000,margin:'48px auto',padding:24,fontFamily:t.sans}}><h1>{names[tab]||'Project workspace'}</h1><p style={{color:t.inkSoft,lineHeight:1.7}}>This module is not connected to your property yet. Your saved property details, unit schedule and planning model are available.</p><button onClick={()=>onNavigate('today')} style={{padding:'12px 18px',background:t.accent,color:'#0a0a0b',border:0,cursor:'pointer'}}>Back to dashboard</button></main>;
}
Object.assign(window,{ProjectDashboard,ProjectModuleEmpty});
